### ISSUE TITLE
Add advise that termios gem is required

### ISSUE THREAD

**Issue by inkel** [jacott/emacs-pry#1]
I've tried to test `emacs-pry` and when I run `run-pry` I've got the following:

```
/Users/inkel/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require
.rb:36:in `require': cannot load such file -- termios (LoadError)                     
        from /Users/inkel/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'                                                      
        from /Users/inkel/.emacs.d/vendor/pry/ruby/emacs_pry.rb:1:in `<top (required)>'
        from /Users/inkel/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'                                                      
        from /Users/inkel/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'                                                      
        from /Users/inkel/.rvm/gems/ruby-1.9.3-p0@global/gems/pry-0.9.8.1/lib/pry/pry_class.rb:72:in `block in load_requires'                                                
        from /Users/inkel/.rvm/gems/ruby-1.9.3-p0@global/gems/pry-0.9.8.1/lib/pry/pry_class.rb:71:in `each'                                                                  
        from /Users/inkel/.rvm/gems/ruby-1.9.3-p0@global/gems/pry-0.9.8.1/lib/pry/pry_class.rb:71:in `load_requires'                                                         
        from /Users/inkel/.rvm/gems/ruby-1.9.3-p0@global/gems/pry-0.9.8.1/lib/pry/pry_cexited abnormally with code 1
in `<topfrom /Users/inkel/.rvm/gems/ruby-1.9.3-p0@global/bin/pry:19:in `<main>'ry:16: 
```

I know I can fix it running `gem install termios` on my command line, though it would be nice to add a requirements section to the README.

**Comment by jacott** [comment]
Thanks for the advise!

I have made termios optional and updated the README

Cheers

Geoff
