### ISSUE TITLE
run-pry error

### ISSUE THREAD

**Issue by MortalCatalyst** [jacott/emacs-pry#4]
When I run run-pry in emacs 24.2 on emacs24 I get the following error.

```
from /usr/local/share/gem
```

s/gems/pry-0.9.10/lib/pry/cli.rb:65:in `block in parse_options'                 
                                                                from /usr/local/s
hare/gems/gems/pry-0.9.10/lib/pry/cli.rb:65:in`each'  
                                                        from /usr/local/share/gem
s/gems/pry-0.9.10/lib/pry/cli.rb:65:in `parse_options'                          
                                                        from /usr/local/share/gem
s/gems/pry-0.9.10/bin/pry:16:in`<top (required)>'  
                                                        from /usr/local/bin/pry:2
3:in `load'                                                                     
                from /usr/local/bin/pry:23:in`<main>'
                                                      exited abnormally with code 1

$ ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]

**Comment by jacott** [comment]
You don't appear to have posted all of the stacktrace and the error message. Can you please resend it?
