### ISSUE TITLE
`block in _emacs_setup': IUCLC bad

### ISSUE THREAD

**Issue by devn** [jacott/emacs-pry#5]
The following error can be reproduced by installing "ruby-termios". "termios" on OSX 10.7 fails to get past make.

/Users/dmw/demacs/vendor/emacs-pry/ruby/emacs_pry.rb:42:in `block in _emacs_setup': IUCLC bad (RuntimeError)
        from /Users/dmw/demacs/vendor/emacs-pry/ruby/emacs_pry.rb:72:in`call'
        from /Users/dmw/demacs/vendor/emacs-pry/ruby/emacs_pry.rb:72:in `block in _emacs_setup'
        from /Users/dmw/demacs/vendor/emacs-pry/ruby/emacs_pry.rb:69:in`each'
        from /Users/dmw/demacs/vendor/emacs-pry/ruby/emacs_pry.rb:69:in `_emacs_setup'
        from /Users/dmw/demacs/vendor/emacs-pry/ruby/emacs_pry.rb:108:in`<top (required)>'
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `requi
re'                                                                                                                
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`requi
re'  
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/pry_class.rb:96:in `
block in load_requires'                                                                                            
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/pry_class.rb:95:in`
each'  
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/pry_class.rb:95:in `load_requires'
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/pry_class.rb:118
:in`initial_session_setup'  
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/pry_class.rb:143
:in `start'                                                                                                    
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-nav-0.2.3/lib/pry-nav/pry_ext.r
b:17:in`start_with_pry_nav'  
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/cli.rb:201:in `b
lock in <top (required)>'                                                                                      
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/cli.rb:70:in`ca
ll'  
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/cli.rb:70:in `bl
ock in parse_options'                                                                                          
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/cli.rb:70:in`ea
ch'  
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/lib/pry/cli.rb:70:in `pa
rse_options'                                                                                                   
        from /Users/dmw/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-0.9.12/bin/pry:16:in`<top (req
uired)>'  
        from /Users/dmw/.rvm/gems/ruby-1.9.3-p327/bin/pry:23:in `load'
        from /Users/dmw/.rvm/gems/ruby-1.9.3-p327/bin/pry:23:in`<main>'
exited abnormally with code 1

**Comment by jacott** [comment]
I've pushed a new version. Does that help?
